services:
  postgres:
    image: postgres:15-alpine
    container_name: xeno_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopify_ingestion_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: xeno_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
